version: '3.8'

services:
  cache-server:
    volumes:
      - squidcache:/var/spool/squid
      - squidlogs:/var/log/squid
      - ./squid.conf:/etc/squid/squid.conf:ro
    environment:
      - TZ=America/Denver
    build:
      context: .
    ports:
      - "3128:3128"
    hostname: local-squid
    image: local-squid-img
    container_name: local-squid
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "1g"
    restart: unless-stopped

volumes:
  squidcache:
    driver: local
  squidlogs:
    driver: local